{%set name = "splits" %}
{%set version = "0.1.5" %}
{%set compress_type = "tar.gz" %}
{%set hash_type = "sha256" %}
{%set hash_val = "aa26aa7543c881291906f44694aa468b14028d24868bc5db305814975220082a" %}
{%set build_num = "0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  skip: True  # [py3k]
  number: 0
  script: python setup.py install

requirements:
  build:
    - python

  run:
    - python
    - boto

test:
  imports:
    - splits
    - splits.readers
    - splits.s3
    - splits.util
    - splits.writers

about:
  home: https://github.com/stitchfix/splits
  license: MIT
  # license_file: No MANIFEST.in - see https://github.com/stitchfix/splits/pull/16
  license_family: MIT
  summary: 'A library for dealing with splittable files'

extra:
  recipe-maintainers:
    - pmlandwehr
