{% set name = "splits" %}
{% set version = "0.1.8" %}
{% set compress_type = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "9154ec5801e325b46f388cec3edd6e365d2b90d0f7e80a2f8bb1ea2d4a99260a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip

  run:
    - python
    - boto
    - nose
    - six

test:
  imports:
    - splits
    - splits.readers
    - splits.s3
    - splits.util
    - splits.writers

about:
  home: https://github.com/stitchfix/splits
  license: MIT
  # license_file: No MANIFEST.in - see https://github.com/stitchfix/splits/pull/16
  license_family: MIT
  summary: 'A library for dealing with splittable files'

extra:
  recipe-maintainers:
    - pmlandwehr
