travis:
  secure:
    BINSTAR_TOKEN: PwESBeR11zxOBXdCncMhfcWrGstCjV8+1asLY84oMA5fghitRsPsPCcnMP9/+HHtXwA13P/T0QoTQ6yXOmocyqCs8siAYVCMiNvDHj4mkH7eyDQ9GwndYCSw3crU2TlbHLsrWCVQI6WQatQX6Le7XaRozmTgy+21Qy7e3uhrGXJbfNpTcH9elZ8Gh02l7VIVq3vkqS8MpOjZYs98H8LbxfTQxvZJBsdqsq6tbq+8JK3jAkEOc8/0BVjdZnyIVmfwA3JZeGCYzSzFKYC6CyDW/4a/oqHkmkXGYe4NRog5WhZZyllPK36OibZRszMQxOuatm3mzCXUq4lXk0jznvfeobSwoiXSc9bKkwY1DntDg4Q/EbrbTQ0KoTAuJVmiCTKjuObfPaNnX+0dro8YBrSVLXPs+QqC1LeJYPpQWN7M6LY42ny9WjKlKTdRmJz9VYScLbauk2rikSQeU/Ba5DXc6WdtKa0R7jjpdhqMNZcdMABqDbklAAfg+Ej30WRf8oGdXm4IUTGkcTPqdLtalsTIe1BX2KsrB/i8PKHV4SEjL06jpV/Ds4uOujSVPHADL2xN8Va7ouOVNYzf6N6TekzeHn3/cy9i8cvM0muxEqnsiToDB/9RvR38jlxjUAOUrZhdLvuiC0BMq3Yc+j6VsYRgoUH57aZu4EXO0WoLRh2zNjA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
