travis:
  secure:
    BINSTAR_TOKEN: nlOMNwPIbzIlRoTWDNO4rX53711GGP/gwxAxF++n6asqUJQcvwMINUuIMkuoEUDsTTznq8Z4XfhkQbKhQja5kywzfXmFik/YQGeiSLmjDzELlKjboF46kfhJHnntnU8/oM88GYGLFcfhBAgxnsd5c4F4mJMu0+2WXTAV7R45WNpknPWLj0fxllPY8AtgdssWp7+uM9iYD4NQSjaG3uVcBGkXUv0uW8s4MIjas8513lT8X4hA/ETYfufQ9Kj/pLyaf0UVMAEe0WlyDiCrVuIfGpdZU3AO15VRK6buJvr/vlcaSyyMFOU1AZuUYRmykaEnoXjHl/v/or/HvCBSOUvxr/wVaoQycrhfVMax65SVwmxHfEZObOo0embecQVeBMvovBNB4MCN1h56Spb/UBxLK74czUXmjtD8SsZIvEMvG00rZ6SHS6ZK3XYWHbRPr2TdEt+9w6gAkNNOq67rOTvuh0rwVB/K2dlzAZpZUbufsJWoh4CFM87sUa0rIfR7V8ddAS93B4p4mV78lsEoCwl3fTpCIHFgzxn5AJaoKEwlIp0H6P2UrcPQOUAw0LedpYKLRNvS9DKn6W2HDpgWJur7NIH/WxAoSTMF7cOJBVu4VhnXZ8zspQhIj2+AXRKQVYfQhpxWRJ90oWBqb9SyZiQrydN0xhR+WijzylzVbR45Au0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
